### PR TITLE
Cat - superior animal now added.

### PR DESCRIPTION
**Pull request by Skjolde**
I was looking for the perfect picture of a cat.

Clearly I succeeded.
Comments?

### CODE REVIEW

**Comment by rainermesi** [comment]
@Skjolde @jjjENSjens I think this cat rocks!

- [ ] test checklist
- [x] no 2 on this list

**Comment by jjjENSjens** [comment]
it like this cat more

**Comment by Skjolde** [comment]
Pope Francis:
>Thou be blessed
>

**Comment by Skjolde** [comment]
![Kitty] (https://www.petworld.dk/resources/category/3_k/at/3%20kat.jpg?width=400&height=230&format=jpg)

**Comment by Skjolde** [comment]
Kitty

**Comment by Skjolde** [comment]
https://www.petworld.dk/resources/category/3_k/at/3%20kat.jpg?width=400&height=230&format=jpg

**Pull request merged**
